apiVersion: v1
kind: ConfigMap
metadata:
  name: sfmc-config
  namespace: sfmc
data:
  NODE_ENV: "production"
  TZ: "UTC"
  LOG_LEVEL: "info"
  HOST: "0.0.0.0"
  DB_USER: "postgres"
  DB_SSL: "false"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  # Inter-services (ClusterIP DNS du namespace sfmc)
  INVENTORY_SERVICE_URL: "http://inventory-service:3004"
  PRODUCT_SERVICE_URL: "http://product-service:3003"
  USER_SERVICE_URL: "http://user-service:3002"
